apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-postgressql-abiudacityproject
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: '10.100.19.227'
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret-abiudacityproject
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==